query pageQuery {
  ...LayoutQueryFragment
  projectConnection {
    edges {
      node {
        id
        title
        excerpt
        heroImg
        tags
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}


query projectQuery($relativePath: String!) {
  ...LayoutQueryFragment
  project(relativePath: $relativePath) {
    ...ProjectParts
  }
}
